### ISSUE TITLE
FEATURE: Add header to slave record in master/slave view

### ISSUE THREAD

**Issue by rswgnu** [ajkerrigan/visidata-plugins#13]
Often the data won't make sense without a header prefix.  You could use the 'dataframe.T' function of Pandas to quickly produce a nicely formatted output if you don't want to write the formatting yourself.

**Comment by ajkerrigan** [comment]
Hi there @rswgnu - I occasionally want headers in detail views too. Are there specific cases where you're missing the context you need? It may be something we can talk through and see if it merits a change (or request) to VisiData proper.

The splitnav plugin doesn't actually construct child sheets, it only adds some convenience keybindings for navigating them. So I'm thinking any time you find a detail sheet without context headers, the same issue would show up even if you're not using the split window feature.

**Comment by ajkerrigan** [comment]
This issue is a bit stale and there are splitpane changes in vd 2.3 that seem likely to require more/different changes in any case.
