### ISSUE TITLE
[feature request] Split navigation should be smart about frequency tables.

### ISSUE THREAD

**Issue by frosencrantz** [ajkerrigan/visidata-plugins#7]
One window could display the frequency table.  As you navigate the SheetFreqTable in one window, the other window shows the rows from the original table matching the cursorRow.

**Comment by ajkerrigan** [comment]
Hmm, that seems like a neat idea @frosencrantz :). I may take a crack at it. I'm not sure if I'd add it to the split navigation plugin or not - that's simplistic and naive by design only covers navigating a master/detail type split. This seems like a useful cousin feature, I just want to avoid painting this plugin as a general purpose split tool. I don't have grand plans for it 😁 .

**Comment by ajkerrigan** [comment]
I got some form of this behavior working in the latest. By default:

* `Alt`+`Enter`: Zoom in on the cursor row
* `Alt`+`j`: Move down one row and zoom
* `Alt`+`k`: Move up one row and zoom

And in this case, 'zoom' means open a disposable sheet where rows from the source match the frequency table cursor row. Demo:

[![asciicast](https://asciinema.org/a/hS2cSpo7rHI2FN0piscFSlRm5.svg)](https://asciinema.org/a/hS2cSpo7rHI2FN0piscFSlRm5)

Thanks for the idea! I wouldn't have done it without a nudge, but now that it's in there I'm reasonably confident that I'll use it 😁 !

**Comment by frosencrantz** [comment]
AJ you rock! 😁 I haven't tried it yet but that looks like what I was thinking.

I was trying to explore some Covid19 data with multiple locations,
and it would have been nice to quickly jump to different locations and see
only the per location data. This feature will allow me to do that!

One future Visidata feature that I think would be useful:
It would be nice if Visidata had a way to condense down the Frequency Table to
a single terminal line, and then allow you to move left/right to select
different values. That way there is more screen for the single location's data. But that
would require a change to Visidata, that I don't think will happen for a while. 
With your very useful extension,  Visidata still will split the in half screen for the FrqTbl.

**Comment by ajkerrigan** [comment]
> I was trying to explore some Covid19 data with multiple locations,
> and it would have been nice to quickly jump to different locations and see
> only the per location data.

Ah, sounds neat! And thanks for sharing the context, that's helpful :).

> One future Visidata feature that I think would be useful:
> It would be nice if Visidata had a way to condense down the Frequency Table to
> a single terminal line, and then allow you to move left/right to select
> different values. That way there is more screen for the single location's data. But that
> would require a change to Visidata, that I don't think will happen for a while.
> With your very useful extension, Visidata still will split the in half screen for the FrqTbl.

Yeah, that does sound like an upstream thing. Although... I wonder if specifying a split with a small percentage of the window (`zZ`) would cover all/most of that use case? In my case if I use a 7% split, it gives a single row frequency table which I can navigate with this plugin. It's not quite the left/right you talked about, but it _does_ let you switch among groups with more real estate devoted to the source data. Maybe at least a decent workaround 🤷‍♂️

[![asciicast](https://asciinema.org/a/MAALDY5g4VGdC96lc8bk4mx2S.svg)](https://asciinema.org/a/MAALDY5g4VGdC96lc8bk4mx2S)

**Comment by frosencrantz** [comment]
AJ, yes that works without too much screen lost.  I haven't started using the split navigation, but I think this works.

Thanks for the suggestion!
