### ISSUE TITLE
Feature Request: kvpairs should look for more key/value names

### ISSUE THREAD

**Issue by frosencrantz** [ajkerrigan/visidata-plugins#8]
Feature request add a way to add additional names as key or value names. 

Currently the values are 'Key' and 'Value'.  I have data that uses 'name' and 'value'.
I think this was in a har file.

This seems to be a common pattern with how data is encoded, it seems like it would be
useful if to look for multiple possible names, and ignore case.

Also, I don't know how your code handles a collision where the same key is listed more than once.

**Comment by ajkerrigan** [comment]
> Feature request add a way to add additional names as key or value names.
> 
> Currently the values are 'Key' and 'Value'. I have data that uses 'name' and 'value'.
> I think this was in a har file.

Sounds reasonable to me. The jq feature that inspired this plugin checks for other naming configurations. I only really use this for expanding AWS resource tags myself. This request gives me a reason to make it more flexible 👍 .

> Also, I don't know how your code handles a collision where the same key is listed more than once.

Last one wins. That appears to match the jq behavior.

**Comment by ajkerrigan** [comment]
Hey @frosencrantz - the latest changes should do the trick for you, give it a shot when you get a chance and let me know how it goes.

**Comment by frosencrantz** [comment]
AJ, I've tried it that works great.  Thanks! 🙏
