### ISSUE TITLE
AttributeError: type object 'Column' has no attribute 'api'

### ISSUE THREAD

**Issue by gkonstanty** [ajkerrigan/visidata-plugins#9]
Hi, thanks for your plugins!
I was trying to install vpager, but I'm receiving following error:
```
# ~/.visidata/plugins/vpager.py #8 
AttributeError: visidata "type object Column has no attribute api"
```

I am using official version from PyPI for Ubuntu: 
```
$ vd  --version
saul.pw/VisiData v1.5.2
```

For which version of visidata is your plugin adjusted? 
Do you know if there any docs about visidata API for writing plugins?

**Comment by ajkerrigan** [comment]
Hiya @gkonstanty ! Thanks for the report, I should probably put the version constraints somewhere prominent.

> For which version of visidata is your plugin adjusted?

The plugins in this repo have all been designed with v2.x in mind. They all _should_ work from the develop branch or the most recent 2.x release (you can find installation instructions [here](https://www.visidata.org/v2.x/)). The official release of VisiData 2.0 seems to be coming quite soon, which should make things a bit more straightforward.

> Do you know if there any docs about visidata API for writing plugins?

What a timely question! There is a VisiData 2.0 plugin guide for authors shaping up [here](https://github.com/saulpw/visidata/tree/develop/docs/api). I've been peeking at it and trying to make sure the plugins in this repo follow that guide's conventions.

**Comment by gkonstanty** [comment]
Thanks for the response and information!
